version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: Family-Event-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

volumes:
  mongodb_data:
    driver: local
